Rails.application.routes.draw do
  get 'welcome/index'
  get 'login'=>'login#index'
  post 'create' => 'login#create'
  post 'login' => 'login#login'	
  post 'select'=> 'login#select'
  get 'users' => 'login#users'
  get 'admin' => 'login#admin'
  #get '/admin'=>'login#admin'
  get 'usermov' => 'login#usermov'
  get 'editactor/admin'=>'login#admin'	
  get 'admin/addmov'=> 'addmov#_addmov'
  get 'users/addmov'=> 'addmov#_addmov'
  get 'admin/actors'=> 'actors#addactors' 
  #get 'admin/actors'=> 'actors#addactors'
  post '_addmov' => 'addmov#_addmov'
  get '_addmov' => 'addmov#_addmov' 
  get 'adddir' => 'directors#adddir'
  post 'adddir' => 'directors#adddir'  	
  get 'addactors'=>'actors#addactors'
  post 'addactors' => 'actors#addactors'
  get 'editactor'=>'actors#editactor'
  get 'editdirector'=>'directors#editdirector'
  post 'editdirector'=>'directors#editdirector'
  get 'destroy'=>'actors#destroy'
  get 'view/viewmov' => 'view#viewmov'
  get 'view/viewact' => 'view#viewact'
  get 'view/viewdir' => 'view#viewdir'
  get 'destroydir'=>'directors#destroydir'
  get 'verifymov'=>'verify#verifymov'
  get 'movieadded'=>'verify#movieadded'
  get 'moviedeleted'=>'verify#moviedeleted'		
  post 'editactor' => 'actors#editactor'
  get 'logout' => 'login#logout'
  get '/welcome/login' => 'login#index'
  post '/welcome/srch' => 'search#srch'
  get '/welcome/srch' => 'welcome#index'
  post '/view/addrating' => 'view#addrating'
  post '/view/comments' => 'view#comments'
  post '/view/srch' => 'search#srch'
  get '/view/srch' => 'search#srch'
  post '/srch' => 'search#srch'
   get '/srch' => 'login#users'
   get 'viewall' => 'view#viewall'
   post '/admin/srch'=> 'search#srch'
  get 'destroycomm'=>'view#destroycomm'
  get 'reportcomm'=>'view#reportcomm'
  get 'verifycomm' => 'verify#verifycomm'
  get 'ignore' => 'verify#ignore'
  get 'commdel' => 'verify#commdel'
  get 'srchgen' => 'search#srchgen'
  root 'welcome#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
